// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent/v1/agent.proto

// Agent API: the shared abc session backend (formerly the Hono/zod-openapi
// surface under /api/v1). The single source of truth for the agent contract.
// Server: agent (TypeScript). Clients: easylab gateway, ext servers, Flutter.
package agentv1connect

import (
	context "context"
	errors "errors"
	v1 "github.com/abcp-sdk/agent-proto/agent/v1"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "agent.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceHealthProcedure is the fully-qualified name of the AgentService's Health RPC.
	AgentServiceHealthProcedure = "/agent.v1.AgentService/Health"
	// AgentServiceListSessionsProcedure is the fully-qualified name of the AgentService's ListSessions
	// RPC.
	AgentServiceListSessionsProcedure = "/agent.v1.AgentService/ListSessions"
	// AgentServiceCreateSessionProcedure is the fully-qualified name of the AgentService's
	// CreateSession RPC.
	AgentServiceCreateSessionProcedure = "/agent.v1.AgentService/CreateSession"
	// AgentServiceGetSessionProcedure is the fully-qualified name of the AgentService's GetSession RPC.
	AgentServiceGetSessionProcedure = "/agent.v1.AgentService/GetSession"
	// AgentServiceDeleteSessionProcedure is the fully-qualified name of the AgentService's
	// DeleteSession RPC.
	AgentServiceDeleteSessionProcedure = "/agent.v1.AgentService/DeleteSession"
	// AgentServiceListMessagesProcedure is the fully-qualified name of the AgentService's ListMessages
	// RPC.
	AgentServiceListMessagesProcedure = "/agent.v1.AgentService/ListMessages"
	// AgentServicePromptProcedure is the fully-qualified name of the AgentService's Prompt RPC.
	AgentServicePromptProcedure = "/agent.v1.AgentService/Prompt"
	// AgentServiceWatchSessionProcedure is the fully-qualified name of the AgentService's WatchSession
	// RPC.
	AgentServiceWatchSessionProcedure = "/agent.v1.AgentService/WatchSession"
	// AgentServiceForkProcedure is the fully-qualified name of the AgentService's Fork RPC.
	AgentServiceForkProcedure = "/agent.v1.AgentService/Fork"
	// AgentServiceRenameProcedure is the fully-qualified name of the AgentService's Rename RPC.
	AgentServiceRenameProcedure = "/agent.v1.AgentService/Rename"
	// AgentServiceSetModelProcedure is the fully-qualified name of the AgentService's SetModel RPC.
	AgentServiceSetModelProcedure = "/agent.v1.AgentService/SetModel"
	// AgentServiceUndoProcedure is the fully-qualified name of the AgentService's Undo RPC.
	AgentServiceUndoProcedure = "/agent.v1.AgentService/Undo"
	// AgentServiceStateProcedure is the fully-qualified name of the AgentService's State RPC.
	AgentServiceStateProcedure = "/agent.v1.AgentService/State"
	// AgentServiceMailboxProcedure is the fully-qualified name of the AgentService's Mailbox RPC.
	AgentServiceMailboxProcedure = "/agent.v1.AgentService/Mailbox"
	// AgentServiceUpdateSettingsProcedure is the fully-qualified name of the AgentService's
	// UpdateSettings RPC.
	AgentServiceUpdateSettingsProcedure = "/agent.v1.AgentService/UpdateSettings"
	// AgentServiceInterruptProcedure is the fully-qualified name of the AgentService's Interrupt RPC.
	AgentServiceInterruptProcedure = "/agent.v1.AgentService/Interrupt"
	// AgentServiceCompactProcedure is the fully-qualified name of the AgentService's Compact RPC.
	AgentServiceCompactProcedure = "/agent.v1.AgentService/Compact"
	// AgentServiceListProvidersProcedure is the fully-qualified name of the AgentService's
	// ListProviders RPC.
	AgentServiceListProvidersProcedure = "/agent.v1.AgentService/ListProviders"
	// AgentServiceListProvidersCatalogProcedure is the fully-qualified name of the AgentService's
	// ListProvidersCatalog RPC.
	AgentServiceListProvidersCatalogProcedure = "/agent.v1.AgentService/ListProvidersCatalog"
	// AgentServiceRegisterProviderProcedure is the fully-qualified name of the AgentService's
	// RegisterProvider RPC.
	AgentServiceRegisterProviderProcedure = "/agent.v1.AgentService/RegisterProvider"
	// AgentServiceDeleteProviderProcedure is the fully-qualified name of the AgentService's
	// DeleteProvider RPC.
	AgentServiceDeleteProviderProcedure = "/agent.v1.AgentService/DeleteProvider"
	// AgentServiceTestProviderProcedure is the fully-qualified name of the AgentService's TestProvider
	// RPC.
	AgentServiceTestProviderProcedure = "/agent.v1.AgentService/TestProvider"
	// AgentServiceListModelsProcedure is the fully-qualified name of the AgentService's ListModels RPC.
	AgentServiceListModelsProcedure = "/agent.v1.AgentService/ListModels"
	// AgentServiceListPresetsProcedure is the fully-qualified name of the AgentService's ListPresets
	// RPC.
	AgentServiceListPresetsProcedure = "/agent.v1.AgentService/ListPresets"
	// AgentServiceUpsertPresetProcedure is the fully-qualified name of the AgentService's UpsertPreset
	// RPC.
	AgentServiceUpsertPresetProcedure = "/agent.v1.AgentService/UpsertPreset"
	// AgentServiceDeletePresetProcedure is the fully-qualified name of the AgentService's DeletePreset
	// RPC.
	AgentServiceDeletePresetProcedure = "/agent.v1.AgentService/DeletePreset"
	// AgentServicePreviewPresetProcedure is the fully-qualified name of the AgentService's
	// PreviewPreset RPC.
	AgentServicePreviewPresetProcedure = "/agent.v1.AgentService/PreviewPreset"
	// AgentServiceGetConfigProcedure is the fully-qualified name of the AgentService's GetConfig RPC.
	AgentServiceGetConfigProcedure = "/agent.v1.AgentService/GetConfig"
	// AgentServiceSetConfigProcedure is the fully-qualified name of the AgentService's SetConfig RPC.
	AgentServiceSetConfigProcedure = "/agent.v1.AgentService/SetConfig"
	// AgentServiceListToolsProcedure is the fully-qualified name of the AgentService's ListTools RPC.
	AgentServiceListToolsProcedure = "/agent.v1.AgentService/ListTools"
	// AgentServiceGetToolConfigProcedure is the fully-qualified name of the AgentService's
	// GetToolConfig RPC.
	AgentServiceGetToolConfigProcedure = "/agent.v1.AgentService/GetToolConfig"
	// AgentServiceSetToolConfigProcedure is the fully-qualified name of the AgentService's
	// SetToolConfig RPC.
	AgentServiceSetToolConfigProcedure = "/agent.v1.AgentService/SetToolConfig"
	// AgentServiceSetExtensionConfigProcedure is the fully-qualified name of the AgentService's
	// SetExtensionConfig RPC.
	AgentServiceSetExtensionConfigProcedure = "/agent.v1.AgentService/SetExtensionConfig"
	// AgentServiceUploadFileProcedure is the fully-qualified name of the AgentService's UploadFile RPC.
	AgentServiceUploadFileProcedure = "/agent.v1.AgentService/UploadFile"
	// AgentServiceIngestFileProcedure is the fully-qualified name of the AgentService's IngestFile RPC.
	AgentServiceIngestFileProcedure = "/agent.v1.AgentService/IngestFile"
	// AgentServiceGetFileProcedure is the fully-qualified name of the AgentService's GetFile RPC.
	AgentServiceGetFileProcedure = "/agent.v1.AgentService/GetFile"
	// AgentServiceGetFileMetaProcedure is the fully-qualified name of the AgentService's GetFileMeta
	// RPC.
	AgentServiceGetFileMetaProcedure = "/agent.v1.AgentService/GetFileMeta"
	// AgentServiceGetAgentConfigProcedure is the fully-qualified name of the AgentService's
	// GetAgentConfig RPC.
	AgentServiceGetAgentConfigProcedure = "/agent.v1.AgentService/GetAgentConfig"
)

// AgentServiceClient is a client for the agent.v1.AgentService service.
type AgentServiceClient interface {
	Health(context.Context, *connect_go.Request[v1.HealthRequest]) (*connect_go.Response[v1.HealthResponse], error)
	ListSessions(context.Context, *connect_go.Request[v1.ListSessionsRequest]) (*connect_go.Response[v1.ListSessionsResponse], error)
	CreateSession(context.Context, *connect_go.Request[v1.CreateSessionRequest]) (*connect_go.Response[v1.CreateSessionResponse], error)
	GetSession(context.Context, *connect_go.Request[v1.GetSessionRequest]) (*connect_go.Response[v1.GetSessionResponse], error)
	DeleteSession(context.Context, *connect_go.Request[v1.DeleteSessionRequest]) (*connect_go.Response[v1.DeleteSessionResponse], error)
	ListMessages(context.Context, *connect_go.Request[v1.ListMessagesRequest]) (*connect_go.Response[v1.ListMessagesResponse], error)
	Prompt(context.Context, *connect_go.Request[v1.PromptRequest]) (*connect_go.ServerStreamForClient[v1.PromptResponse], error)
	WatchSession(context.Context, *connect_go.Request[v1.WatchSessionRequest]) (*connect_go.ServerStreamForClient[v1.WatchSessionResponse], error)
	Fork(context.Context, *connect_go.Request[v1.ForkRequest]) (*connect_go.Response[v1.ForkResponse], error)
	Rename(context.Context, *connect_go.Request[v1.RenameRequest]) (*connect_go.Response[v1.RenameResponse], error)
	SetModel(context.Context, *connect_go.Request[v1.SetModelRequest]) (*connect_go.Response[v1.SetModelResponse], error)
	Undo(context.Context, *connect_go.Request[v1.UndoRequest]) (*connect_go.Response[v1.UndoResponse], error)
	State(context.Context, *connect_go.Request[v1.StateRequest]) (*connect_go.Response[v1.StateResponse], error)
	Mailbox(context.Context, *connect_go.Request[v1.MailboxRequest]) (*connect_go.Response[v1.MailboxResponse], error)
	UpdateSettings(context.Context, *connect_go.Request[v1.UpdateSettingsRequest]) (*connect_go.Response[v1.UpdateSettingsResponse], error)
	Interrupt(context.Context, *connect_go.Request[v1.InterruptRequest]) (*connect_go.Response[v1.InterruptResponse], error)
	Compact(context.Context, *connect_go.Request[v1.CompactRequest]) (*connect_go.Response[v1.CompactResponse], error)
	ListProviders(context.Context, *connect_go.Request[v1.ListProvidersRequest]) (*connect_go.Response[v1.ListProvidersResponse], error)
	ListProvidersCatalog(context.Context, *connect_go.Request[v1.ListProvidersCatalogRequest]) (*connect_go.Response[v1.ListProvidersCatalogResponse], error)
	RegisterProvider(context.Context, *connect_go.Request[v1.RegisterProviderRequest]) (*connect_go.Response[v1.RegisterProviderResponse], error)
	DeleteProvider(context.Context, *connect_go.Request[v1.DeleteProviderRequest]) (*connect_go.Response[v1.DeleteProviderResponse], error)
	TestProvider(context.Context, *connect_go.Request[v1.TestProviderRequest]) (*connect_go.Response[v1.TestProviderResponse], error)
	ListModels(context.Context, *connect_go.Request[v1.ListModelsRequest]) (*connect_go.Response[v1.ListModelsResponse], error)
	ListPresets(context.Context, *connect_go.Request[v1.ListPresetsRequest]) (*connect_go.Response[v1.ListPresetsResponse], error)
	UpsertPreset(context.Context, *connect_go.Request[v1.UpsertPresetRequest]) (*connect_go.Response[v1.UpsertPresetResponse], error)
	DeletePreset(context.Context, *connect_go.Request[v1.DeletePresetRequest]) (*connect_go.Response[v1.DeletePresetResponse], error)
	PreviewPreset(context.Context, *connect_go.Request[v1.PreviewPresetRequest]) (*connect_go.Response[v1.PreviewPresetResponse], error)
	GetConfig(context.Context, *connect_go.Request[v1.GetConfigRequest]) (*connect_go.Response[v1.GetConfigResponse], error)
	SetConfig(context.Context, *connect_go.Request[v1.SetConfigRequest]) (*connect_go.Response[v1.SetConfigResponse], error)
	ListTools(context.Context, *connect_go.Request[v1.ListToolsRequest]) (*connect_go.Response[v1.ListToolsResponse], error)
	GetToolConfig(context.Context, *connect_go.Request[v1.GetToolConfigRequest]) (*connect_go.Response[v1.GetToolConfigResponse], error)
	SetToolConfig(context.Context, *connect_go.Request[v1.SetToolConfigRequest]) (*connect_go.Response[v1.SetToolConfigResponse], error)
	SetExtensionConfig(context.Context, *connect_go.Request[v1.SetExtensionConfigRequest]) (*connect_go.Response[v1.SetExtensionConfigResponse], error)
	UploadFile(context.Context, *connect_go.Request[v1.UploadFileRequest]) (*connect_go.Response[v1.UploadFileResponse], error)
	IngestFile(context.Context, *connect_go.Request[v1.IngestFileRequest]) (*connect_go.Response[v1.IngestFileResponse], error)
	GetFile(context.Context, *connect_go.Request[v1.GetFileRequest]) (*connect_go.Response[v1.GetFileResponse], error)
	GetFileMeta(context.Context, *connect_go.Request[v1.GetFileMetaRequest]) (*connect_go.Response[v1.GetFileMetaResponse], error)
	GetAgentConfig(context.Context, *connect_go.Request[v1.GetAgentConfigRequest]) (*connect_go.Response[v1.GetAgentConfigResponse], error)
}

// NewAgentServiceClient constructs a client for the agent.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &agentServiceClient{
		health: connect_go.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+AgentServiceHealthProcedure,
			opts...,
		),
		listSessions: connect_go.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+AgentServiceListSessionsProcedure,
			opts...,
		),
		createSession: connect_go.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+AgentServiceCreateSessionProcedure,
			opts...,
		),
		getSession: connect_go.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+AgentServiceGetSessionProcedure,
			opts...,
		),
		deleteSession: connect_go.NewClient[v1.DeleteSessionRequest, v1.DeleteSessionResponse](
			httpClient,
			baseURL+AgentServiceDeleteSessionProcedure,
			opts...,
		),
		listMessages: connect_go.NewClient[v1.ListMessagesRequest, v1.ListMessagesResponse](
			httpClient,
			baseURL+AgentServiceListMessagesProcedure,
			opts...,
		),
		prompt: connect_go.NewClient[v1.PromptRequest, v1.PromptResponse](
			httpClient,
			baseURL+AgentServicePromptProcedure,
			opts...,
		),
		watchSession: connect_go.NewClient[v1.WatchSessionRequest, v1.WatchSessionResponse](
			httpClient,
			baseURL+AgentServiceWatchSessionProcedure,
			opts...,
		),
		fork: connect_go.NewClient[v1.ForkRequest, v1.ForkResponse](
			httpClient,
			baseURL+AgentServiceForkProcedure,
			opts...,
		),
		rename: connect_go.NewClient[v1.RenameRequest, v1.RenameResponse](
			httpClient,
			baseURL+AgentServiceRenameProcedure,
			opts...,
		),
		setModel: connect_go.NewClient[v1.SetModelRequest, v1.SetModelResponse](
			httpClient,
			baseURL+AgentServiceSetModelProcedure,
			opts...,
		),
		undo: connect_go.NewClient[v1.UndoRequest, v1.UndoResponse](
			httpClient,
			baseURL+AgentServiceUndoProcedure,
			opts...,
		),
		state: connect_go.NewClient[v1.StateRequest, v1.StateResponse](
			httpClient,
			baseURL+AgentServiceStateProcedure,
			opts...,
		),
		mailbox: connect_go.NewClient[v1.MailboxRequest, v1.MailboxResponse](
			httpClient,
			baseURL+AgentServiceMailboxProcedure,
			opts...,
		),
		updateSettings: connect_go.NewClient[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse](
			httpClient,
			baseURL+AgentServiceUpdateSettingsProcedure,
			opts...,
		),
		interrupt: connect_go.NewClient[v1.InterruptRequest, v1.InterruptResponse](
			httpClient,
			baseURL+AgentServiceInterruptProcedure,
			opts...,
		),
		compact: connect_go.NewClient[v1.CompactRequest, v1.CompactResponse](
			httpClient,
			baseURL+AgentServiceCompactProcedure,
			opts...,
		),
		listProviders: connect_go.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+AgentServiceListProvidersProcedure,
			opts...,
		),
		listProvidersCatalog: connect_go.NewClient[v1.ListProvidersCatalogRequest, v1.ListProvidersCatalogResponse](
			httpClient,
			baseURL+AgentServiceListProvidersCatalogProcedure,
			opts...,
		),
		registerProvider: connect_go.NewClient[v1.RegisterProviderRequest, v1.RegisterProviderResponse](
			httpClient,
			baseURL+AgentServiceRegisterProviderProcedure,
			opts...,
		),
		deleteProvider: connect_go.NewClient[v1.DeleteProviderRequest, v1.DeleteProviderResponse](
			httpClient,
			baseURL+AgentServiceDeleteProviderProcedure,
			opts...,
		),
		testProvider: connect_go.NewClient[v1.TestProviderRequest, v1.TestProviderResponse](
			httpClient,
			baseURL+AgentServiceTestProviderProcedure,
			opts...,
		),
		listModels: connect_go.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+AgentServiceListModelsProcedure,
			opts...,
		),
		listPresets: connect_go.NewClient[v1.ListPresetsRequest, v1.ListPresetsResponse](
			httpClient,
			baseURL+AgentServiceListPresetsProcedure,
			opts...,
		),
		upsertPreset: connect_go.NewClient[v1.UpsertPresetRequest, v1.UpsertPresetResponse](
			httpClient,
			baseURL+AgentServiceUpsertPresetProcedure,
			opts...,
		),
		deletePreset: connect_go.NewClient[v1.DeletePresetRequest, v1.DeletePresetResponse](
			httpClient,
			baseURL+AgentServiceDeletePresetProcedure,
			opts...,
		),
		previewPreset: connect_go.NewClient[v1.PreviewPresetRequest, v1.PreviewPresetResponse](
			httpClient,
			baseURL+AgentServicePreviewPresetProcedure,
			opts...,
		),
		getConfig: connect_go.NewClient[v1.GetConfigRequest, v1.GetConfigResponse](
			httpClient,
			baseURL+AgentServiceGetConfigProcedure,
			opts...,
		),
		setConfig: connect_go.NewClient[v1.SetConfigRequest, v1.SetConfigResponse](
			httpClient,
			baseURL+AgentServiceSetConfigProcedure,
			opts...,
		),
		listTools: connect_go.NewClient[v1.ListToolsRequest, v1.ListToolsResponse](
			httpClient,
			baseURL+AgentServiceListToolsProcedure,
			opts...,
		),
		getToolConfig: connect_go.NewClient[v1.GetToolConfigRequest, v1.GetToolConfigResponse](
			httpClient,
			baseURL+AgentServiceGetToolConfigProcedure,
			opts...,
		),
		setToolConfig: connect_go.NewClient[v1.SetToolConfigRequest, v1.SetToolConfigResponse](
			httpClient,
			baseURL+AgentServiceSetToolConfigProcedure,
			opts...,
		),
		setExtensionConfig: connect_go.NewClient[v1.SetExtensionConfigRequest, v1.SetExtensionConfigResponse](
			httpClient,
			baseURL+AgentServiceSetExtensionConfigProcedure,
			opts...,
		),
		uploadFile: connect_go.NewClient[v1.UploadFileRequest, v1.UploadFileResponse](
			httpClient,
			baseURL+AgentServiceUploadFileProcedure,
			opts...,
		),
		ingestFile: connect_go.NewClient[v1.IngestFileRequest, v1.IngestFileResponse](
			httpClient,
			baseURL+AgentServiceIngestFileProcedure,
			opts...,
		),
		getFile: connect_go.NewClient[v1.GetFileRequest, v1.GetFileResponse](
			httpClient,
			baseURL+AgentServiceGetFileProcedure,
			opts...,
		),
		getFileMeta: connect_go.NewClient[v1.GetFileMetaRequest, v1.GetFileMetaResponse](
			httpClient,
			baseURL+AgentServiceGetFileMetaProcedure,
			opts...,
		),
		getAgentConfig: connect_go.NewClient[v1.GetAgentConfigRequest, v1.GetAgentConfigResponse](
			httpClient,
			baseURL+AgentServiceGetAgentConfigProcedure,
			opts...,
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	health               *connect_go.Client[v1.HealthRequest, v1.HealthResponse]
	listSessions         *connect_go.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	createSession        *connect_go.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	getSession           *connect_go.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	deleteSession        *connect_go.Client[v1.DeleteSessionRequest, v1.DeleteSessionResponse]
	listMessages         *connect_go.Client[v1.ListMessagesRequest, v1.ListMessagesResponse]
	prompt               *connect_go.Client[v1.PromptRequest, v1.PromptResponse]
	watchSession         *connect_go.Client[v1.WatchSessionRequest, v1.WatchSessionResponse]
	fork                 *connect_go.Client[v1.ForkRequest, v1.ForkResponse]
	rename               *connect_go.Client[v1.RenameRequest, v1.RenameResponse]
	setModel             *connect_go.Client[v1.SetModelRequest, v1.SetModelResponse]
	undo                 *connect_go.Client[v1.UndoRequest, v1.UndoResponse]
	state                *connect_go.Client[v1.StateRequest, v1.StateResponse]
	mailbox              *connect_go.Client[v1.MailboxRequest, v1.MailboxResponse]
	updateSettings       *connect_go.Client[v1.UpdateSettingsRequest, v1.UpdateSettingsResponse]
	interrupt            *connect_go.Client[v1.InterruptRequest, v1.InterruptResponse]
	compact              *connect_go.Client[v1.CompactRequest, v1.CompactResponse]
	listProviders        *connect_go.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	listProvidersCatalog *connect_go.Client[v1.ListProvidersCatalogRequest, v1.ListProvidersCatalogResponse]
	registerProvider     *connect_go.Client[v1.RegisterProviderRequest, v1.RegisterProviderResponse]
	deleteProvider       *connect_go.Client[v1.DeleteProviderRequest, v1.DeleteProviderResponse]
	testProvider         *connect_go.Client[v1.TestProviderRequest, v1.TestProviderResponse]
	listModels           *connect_go.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	listPresets          *connect_go.Client[v1.ListPresetsRequest, v1.ListPresetsResponse]
	upsertPreset         *connect_go.Client[v1.UpsertPresetRequest, v1.UpsertPresetResponse]
	deletePreset         *connect_go.Client[v1.DeletePresetRequest, v1.DeletePresetResponse]
	previewPreset        *connect_go.Client[v1.PreviewPresetRequest, v1.PreviewPresetResponse]
	getConfig            *connect_go.Client[v1.GetConfigRequest, v1.GetConfigResponse]
	setConfig            *connect_go.Client[v1.SetConfigRequest, v1.SetConfigResponse]
	listTools            *connect_go.Client[v1.ListToolsRequest, v1.ListToolsResponse]
	getToolConfig        *connect_go.Client[v1.GetToolConfigRequest, v1.GetToolConfigResponse]
	setToolConfig        *connect_go.Client[v1.SetToolConfigRequest, v1.SetToolConfigResponse]
	setExtensionConfig   *connect_go.Client[v1.SetExtensionConfigRequest, v1.SetExtensionConfigResponse]
	uploadFile           *connect_go.Client[v1.UploadFileRequest, v1.UploadFileResponse]
	ingestFile           *connect_go.Client[v1.IngestFileRequest, v1.IngestFileResponse]
	getFile              *connect_go.Client[v1.GetFileRequest, v1.GetFileResponse]
	getFileMeta          *connect_go.Client[v1.GetFileMetaRequest, v1.GetFileMetaResponse]
	getAgentConfig       *connect_go.Client[v1.GetAgentConfigRequest, v1.GetAgentConfigResponse]
}

// Health calls agent.v1.AgentService.Health.
func (c *agentServiceClient) Health(ctx context.Context, req *connect_go.Request[v1.HealthRequest]) (*connect_go.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// ListSessions calls agent.v1.AgentService.ListSessions.
func (c *agentServiceClient) ListSessions(ctx context.Context, req *connect_go.Request[v1.ListSessionsRequest]) (*connect_go.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// CreateSession calls agent.v1.AgentService.CreateSession.
func (c *agentServiceClient) CreateSession(ctx context.Context, req *connect_go.Request[v1.CreateSessionRequest]) (*connect_go.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// GetSession calls agent.v1.AgentService.GetSession.
func (c *agentServiceClient) GetSession(ctx context.Context, req *connect_go.Request[v1.GetSessionRequest]) (*connect_go.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// DeleteSession calls agent.v1.AgentService.DeleteSession.
func (c *agentServiceClient) DeleteSession(ctx context.Context, req *connect_go.Request[v1.DeleteSessionRequest]) (*connect_go.Response[v1.DeleteSessionResponse], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// ListMessages calls agent.v1.AgentService.ListMessages.
func (c *agentServiceClient) ListMessages(ctx context.Context, req *connect_go.Request[v1.ListMessagesRequest]) (*connect_go.Response[v1.ListMessagesResponse], error) {
	return c.listMessages.CallUnary(ctx, req)
}

// Prompt calls agent.v1.AgentService.Prompt.
func (c *agentServiceClient) Prompt(ctx context.Context, req *connect_go.Request[v1.PromptRequest]) (*connect_go.ServerStreamForClient[v1.PromptResponse], error) {
	return c.prompt.CallServerStream(ctx, req)
}

// WatchSession calls agent.v1.AgentService.WatchSession.
func (c *agentServiceClient) WatchSession(ctx context.Context, req *connect_go.Request[v1.WatchSessionRequest]) (*connect_go.ServerStreamForClient[v1.WatchSessionResponse], error) {
	return c.watchSession.CallServerStream(ctx, req)
}

// Fork calls agent.v1.AgentService.Fork.
func (c *agentServiceClient) Fork(ctx context.Context, req *connect_go.Request[v1.ForkRequest]) (*connect_go.Response[v1.ForkResponse], error) {
	return c.fork.CallUnary(ctx, req)
}

// Rename calls agent.v1.AgentService.Rename.
func (c *agentServiceClient) Rename(ctx context.Context, req *connect_go.Request[v1.RenameRequest]) (*connect_go.Response[v1.RenameResponse], error) {
	return c.rename.CallUnary(ctx, req)
}

// SetModel calls agent.v1.AgentService.SetModel.
func (c *agentServiceClient) SetModel(ctx context.Context, req *connect_go.Request[v1.SetModelRequest]) (*connect_go.Response[v1.SetModelResponse], error) {
	return c.setModel.CallUnary(ctx, req)
}

// Undo calls agent.v1.AgentService.Undo.
func (c *agentServiceClient) Undo(ctx context.Context, req *connect_go.Request[v1.UndoRequest]) (*connect_go.Response[v1.UndoResponse], error) {
	return c.undo.CallUnary(ctx, req)
}

// State calls agent.v1.AgentService.State.
func (c *agentServiceClient) State(ctx context.Context, req *connect_go.Request[v1.StateRequest]) (*connect_go.Response[v1.StateResponse], error) {
	return c.state.CallUnary(ctx, req)
}

// Mailbox calls agent.v1.AgentService.Mailbox.
func (c *agentServiceClient) Mailbox(ctx context.Context, req *connect_go.Request[v1.MailboxRequest]) (*connect_go.Response[v1.MailboxResponse], error) {
	return c.mailbox.CallUnary(ctx, req)
}

// UpdateSettings calls agent.v1.AgentService.UpdateSettings.
func (c *agentServiceClient) UpdateSettings(ctx context.Context, req *connect_go.Request[v1.UpdateSettingsRequest]) (*connect_go.Response[v1.UpdateSettingsResponse], error) {
	return c.updateSettings.CallUnary(ctx, req)
}

// Interrupt calls agent.v1.AgentService.Interrupt.
func (c *agentServiceClient) Interrupt(ctx context.Context, req *connect_go.Request[v1.InterruptRequest]) (*connect_go.Response[v1.InterruptResponse], error) {
	return c.interrupt.CallUnary(ctx, req)
}

// Compact calls agent.v1.AgentService.Compact.
func (c *agentServiceClient) Compact(ctx context.Context, req *connect_go.Request[v1.CompactRequest]) (*connect_go.Response[v1.CompactResponse], error) {
	return c.compact.CallUnary(ctx, req)
}

// ListProviders calls agent.v1.AgentService.ListProviders.
func (c *agentServiceClient) ListProviders(ctx context.Context, req *connect_go.Request[v1.ListProvidersRequest]) (*connect_go.Response[v1.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// ListProvidersCatalog calls agent.v1.AgentService.ListProvidersCatalog.
func (c *agentServiceClient) ListProvidersCatalog(ctx context.Context, req *connect_go.Request[v1.ListProvidersCatalogRequest]) (*connect_go.Response[v1.ListProvidersCatalogResponse], error) {
	return c.listProvidersCatalog.CallUnary(ctx, req)
}

// RegisterProvider calls agent.v1.AgentService.RegisterProvider.
func (c *agentServiceClient) RegisterProvider(ctx context.Context, req *connect_go.Request[v1.RegisterProviderRequest]) (*connect_go.Response[v1.RegisterProviderResponse], error) {
	return c.registerProvider.CallUnary(ctx, req)
}

// DeleteProvider calls agent.v1.AgentService.DeleteProvider.
func (c *agentServiceClient) DeleteProvider(ctx context.Context, req *connect_go.Request[v1.DeleteProviderRequest]) (*connect_go.Response[v1.DeleteProviderResponse], error) {
	return c.deleteProvider.CallUnary(ctx, req)
}

// TestProvider calls agent.v1.AgentService.TestProvider.
func (c *agentServiceClient) TestProvider(ctx context.Context, req *connect_go.Request[v1.TestProviderRequest]) (*connect_go.Response[v1.TestProviderResponse], error) {
	return c.testProvider.CallUnary(ctx, req)
}

// ListModels calls agent.v1.AgentService.ListModels.
func (c *agentServiceClient) ListModels(ctx context.Context, req *connect_go.Request[v1.ListModelsRequest]) (*connect_go.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// ListPresets calls agent.v1.AgentService.ListPresets.
func (c *agentServiceClient) ListPresets(ctx context.Context, req *connect_go.Request[v1.ListPresetsRequest]) (*connect_go.Response[v1.ListPresetsResponse], error) {
	return c.listPresets.CallUnary(ctx, req)
}

// UpsertPreset calls agent.v1.AgentService.UpsertPreset.
func (c *agentServiceClient) UpsertPreset(ctx context.Context, req *connect_go.Request[v1.UpsertPresetRequest]) (*connect_go.Response[v1.UpsertPresetResponse], error) {
	return c.upsertPreset.CallUnary(ctx, req)
}

// DeletePreset calls agent.v1.AgentService.DeletePreset.
func (c *agentServiceClient) DeletePreset(ctx context.Context, req *connect_go.Request[v1.DeletePresetRequest]) (*connect_go.Response[v1.DeletePresetResponse], error) {
	return c.deletePreset.CallUnary(ctx, req)
}

// PreviewPreset calls agent.v1.AgentService.PreviewPreset.
func (c *agentServiceClient) PreviewPreset(ctx context.Context, req *connect_go.Request[v1.PreviewPresetRequest]) (*connect_go.Response[v1.PreviewPresetResponse], error) {
	return c.previewPreset.CallUnary(ctx, req)
}

// GetConfig calls agent.v1.AgentService.GetConfig.
func (c *agentServiceClient) GetConfig(ctx context.Context, req *connect_go.Request[v1.GetConfigRequest]) (*connect_go.Response[v1.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// SetConfig calls agent.v1.AgentService.SetConfig.
func (c *agentServiceClient) SetConfig(ctx context.Context, req *connect_go.Request[v1.SetConfigRequest]) (*connect_go.Response[v1.SetConfigResponse], error) {
	return c.setConfig.CallUnary(ctx, req)
}

// ListTools calls agent.v1.AgentService.ListTools.
func (c *agentServiceClient) ListTools(ctx context.Context, req *connect_go.Request[v1.ListToolsRequest]) (*connect_go.Response[v1.ListToolsResponse], error) {
	return c.listTools.CallUnary(ctx, req)
}

// GetToolConfig calls agent.v1.AgentService.GetToolConfig.
func (c *agentServiceClient) GetToolConfig(ctx context.Context, req *connect_go.Request[v1.GetToolConfigRequest]) (*connect_go.Response[v1.GetToolConfigResponse], error) {
	return c.getToolConfig.CallUnary(ctx, req)
}

// SetToolConfig calls agent.v1.AgentService.SetToolConfig.
func (c *agentServiceClient) SetToolConfig(ctx context.Context, req *connect_go.Request[v1.SetToolConfigRequest]) (*connect_go.Response[v1.SetToolConfigResponse], error) {
	return c.setToolConfig.CallUnary(ctx, req)
}

// SetExtensionConfig calls agent.v1.AgentService.SetExtensionConfig.
func (c *agentServiceClient) SetExtensionConfig(ctx context.Context, req *connect_go.Request[v1.SetExtensionConfigRequest]) (*connect_go.Response[v1.SetExtensionConfigResponse], error) {
	return c.setExtensionConfig.CallUnary(ctx, req)
}

// UploadFile calls agent.v1.AgentService.UploadFile.
func (c *agentServiceClient) UploadFile(ctx context.Context, req *connect_go.Request[v1.UploadFileRequest]) (*connect_go.Response[v1.UploadFileResponse], error) {
	return c.uploadFile.CallUnary(ctx, req)
}

// IngestFile calls agent.v1.AgentService.IngestFile.
func (c *agentServiceClient) IngestFile(ctx context.Context, req *connect_go.Request[v1.IngestFileRequest]) (*connect_go.Response[v1.IngestFileResponse], error) {
	return c.ingestFile.CallUnary(ctx, req)
}

// GetFile calls agent.v1.AgentService.GetFile.
func (c *agentServiceClient) GetFile(ctx context.Context, req *connect_go.Request[v1.GetFileRequest]) (*connect_go.Response[v1.GetFileResponse], error) {
	return c.getFile.CallUnary(ctx, req)
}

// GetFileMeta calls agent.v1.AgentService.GetFileMeta.
func (c *agentServiceClient) GetFileMeta(ctx context.Context, req *connect_go.Request[v1.GetFileMetaRequest]) (*connect_go.Response[v1.GetFileMetaResponse], error) {
	return c.getFileMeta.CallUnary(ctx, req)
}

// GetAgentConfig calls agent.v1.AgentService.GetAgentConfig.
func (c *agentServiceClient) GetAgentConfig(ctx context.Context, req *connect_go.Request[v1.GetAgentConfigRequest]) (*connect_go.Response[v1.GetAgentConfigResponse], error) {
	return c.getAgentConfig.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the agent.v1.AgentService service.
type AgentServiceHandler interface {
	Health(context.Context, *connect_go.Request[v1.HealthRequest]) (*connect_go.Response[v1.HealthResponse], error)
	ListSessions(context.Context, *connect_go.Request[v1.ListSessionsRequest]) (*connect_go.Response[v1.ListSessionsResponse], error)
	CreateSession(context.Context, *connect_go.Request[v1.CreateSessionRequest]) (*connect_go.Response[v1.CreateSessionResponse], error)
	GetSession(context.Context, *connect_go.Request[v1.GetSessionRequest]) (*connect_go.Response[v1.GetSessionResponse], error)
	DeleteSession(context.Context, *connect_go.Request[v1.DeleteSessionRequest]) (*connect_go.Response[v1.DeleteSessionResponse], error)
	ListMessages(context.Context, *connect_go.Request[v1.ListMessagesRequest]) (*connect_go.Response[v1.ListMessagesResponse], error)
	Prompt(context.Context, *connect_go.Request[v1.PromptRequest], *connect_go.ServerStream[v1.PromptResponse]) error
	WatchSession(context.Context, *connect_go.Request[v1.WatchSessionRequest], *connect_go.ServerStream[v1.WatchSessionResponse]) error
	Fork(context.Context, *connect_go.Request[v1.ForkRequest]) (*connect_go.Response[v1.ForkResponse], error)
	Rename(context.Context, *connect_go.Request[v1.RenameRequest]) (*connect_go.Response[v1.RenameResponse], error)
	SetModel(context.Context, *connect_go.Request[v1.SetModelRequest]) (*connect_go.Response[v1.SetModelResponse], error)
	Undo(context.Context, *connect_go.Request[v1.UndoRequest]) (*connect_go.Response[v1.UndoResponse], error)
	State(context.Context, *connect_go.Request[v1.StateRequest]) (*connect_go.Response[v1.StateResponse], error)
	Mailbox(context.Context, *connect_go.Request[v1.MailboxRequest]) (*connect_go.Response[v1.MailboxResponse], error)
	UpdateSettings(context.Context, *connect_go.Request[v1.UpdateSettingsRequest]) (*connect_go.Response[v1.UpdateSettingsResponse], error)
	Interrupt(context.Context, *connect_go.Request[v1.InterruptRequest]) (*connect_go.Response[v1.InterruptResponse], error)
	Compact(context.Context, *connect_go.Request[v1.CompactRequest]) (*connect_go.Response[v1.CompactResponse], error)
	ListProviders(context.Context, *connect_go.Request[v1.ListProvidersRequest]) (*connect_go.Response[v1.ListProvidersResponse], error)
	ListProvidersCatalog(context.Context, *connect_go.Request[v1.ListProvidersCatalogRequest]) (*connect_go.Response[v1.ListProvidersCatalogResponse], error)
	RegisterProvider(context.Context, *connect_go.Request[v1.RegisterProviderRequest]) (*connect_go.Response[v1.RegisterProviderResponse], error)
	DeleteProvider(context.Context, *connect_go.Request[v1.DeleteProviderRequest]) (*connect_go.Response[v1.DeleteProviderResponse], error)
	TestProvider(context.Context, *connect_go.Request[v1.TestProviderRequest]) (*connect_go.Response[v1.TestProviderResponse], error)
	ListModels(context.Context, *connect_go.Request[v1.ListModelsRequest]) (*connect_go.Response[v1.ListModelsResponse], error)
	ListPresets(context.Context, *connect_go.Request[v1.ListPresetsRequest]) (*connect_go.Response[v1.ListPresetsResponse], error)
	UpsertPreset(context.Context, *connect_go.Request[v1.UpsertPresetRequest]) (*connect_go.Response[v1.UpsertPresetResponse], error)
	DeletePreset(context.Context, *connect_go.Request[v1.DeletePresetRequest]) (*connect_go.Response[v1.DeletePresetResponse], error)
	PreviewPreset(context.Context, *connect_go.Request[v1.PreviewPresetRequest]) (*connect_go.Response[v1.PreviewPresetResponse], error)
	GetConfig(context.Context, *connect_go.Request[v1.GetConfigRequest]) (*connect_go.Response[v1.GetConfigResponse], error)
	SetConfig(context.Context, *connect_go.Request[v1.SetConfigRequest]) (*connect_go.Response[v1.SetConfigResponse], error)
	ListTools(context.Context, *connect_go.Request[v1.ListToolsRequest]) (*connect_go.Response[v1.ListToolsResponse], error)
	GetToolConfig(context.Context, *connect_go.Request[v1.GetToolConfigRequest]) (*connect_go.Response[v1.GetToolConfigResponse], error)
	SetToolConfig(context.Context, *connect_go.Request[v1.SetToolConfigRequest]) (*connect_go.Response[v1.SetToolConfigResponse], error)
	SetExtensionConfig(context.Context, *connect_go.Request[v1.SetExtensionConfigRequest]) (*connect_go.Response[v1.SetExtensionConfigResponse], error)
	UploadFile(context.Context, *connect_go.Request[v1.UploadFileRequest]) (*connect_go.Response[v1.UploadFileResponse], error)
	IngestFile(context.Context, *connect_go.Request[v1.IngestFileRequest]) (*connect_go.Response[v1.IngestFileResponse], error)
	GetFile(context.Context, *connect_go.Request[v1.GetFileRequest]) (*connect_go.Response[v1.GetFileResponse], error)
	GetFileMeta(context.Context, *connect_go.Request[v1.GetFileMetaRequest]) (*connect_go.Response[v1.GetFileMetaResponse], error)
	GetAgentConfig(context.Context, *connect_go.Request[v1.GetAgentConfigRequest]) (*connect_go.Response[v1.GetAgentConfigResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	agentServiceHealthHandler := connect_go.NewUnaryHandler(
		AgentServiceHealthProcedure,
		svc.Health,
		opts...,
	)
	agentServiceListSessionsHandler := connect_go.NewUnaryHandler(
		AgentServiceListSessionsProcedure,
		svc.ListSessions,
		opts...,
	)
	agentServiceCreateSessionHandler := connect_go.NewUnaryHandler(
		AgentServiceCreateSessionProcedure,
		svc.CreateSession,
		opts...,
	)
	agentServiceGetSessionHandler := connect_go.NewUnaryHandler(
		AgentServiceGetSessionProcedure,
		svc.GetSession,
		opts...,
	)
	agentServiceDeleteSessionHandler := connect_go.NewUnaryHandler(
		AgentServiceDeleteSessionProcedure,
		svc.DeleteSession,
		opts...,
	)
	agentServiceListMessagesHandler := connect_go.NewUnaryHandler(
		AgentServiceListMessagesProcedure,
		svc.ListMessages,
		opts...,
	)
	agentServicePromptHandler := connect_go.NewServerStreamHandler(
		AgentServicePromptProcedure,
		svc.Prompt,
		opts...,
	)
	agentServiceWatchSessionHandler := connect_go.NewServerStreamHandler(
		AgentServiceWatchSessionProcedure,
		svc.WatchSession,
		opts...,
	)
	agentServiceForkHandler := connect_go.NewUnaryHandler(
		AgentServiceForkProcedure,
		svc.Fork,
		opts...,
	)
	agentServiceRenameHandler := connect_go.NewUnaryHandler(
		AgentServiceRenameProcedure,
		svc.Rename,
		opts...,
	)
	agentServiceSetModelHandler := connect_go.NewUnaryHandler(
		AgentServiceSetModelProcedure,
		svc.SetModel,
		opts...,
	)
	agentServiceUndoHandler := connect_go.NewUnaryHandler(
		AgentServiceUndoProcedure,
		svc.Undo,
		opts...,
	)
	agentServiceStateHandler := connect_go.NewUnaryHandler(
		AgentServiceStateProcedure,
		svc.State,
		opts...,
	)
	agentServiceMailboxHandler := connect_go.NewUnaryHandler(
		AgentServiceMailboxProcedure,
		svc.Mailbox,
		opts...,
	)
	agentServiceUpdateSettingsHandler := connect_go.NewUnaryHandler(
		AgentServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		opts...,
	)
	agentServiceInterruptHandler := connect_go.NewUnaryHandler(
		AgentServiceInterruptProcedure,
		svc.Interrupt,
		opts...,
	)
	agentServiceCompactHandler := connect_go.NewUnaryHandler(
		AgentServiceCompactProcedure,
		svc.Compact,
		opts...,
	)
	agentServiceListProvidersHandler := connect_go.NewUnaryHandler(
		AgentServiceListProvidersProcedure,
		svc.ListProviders,
		opts...,
	)
	agentServiceListProvidersCatalogHandler := connect_go.NewUnaryHandler(
		AgentServiceListProvidersCatalogProcedure,
		svc.ListProvidersCatalog,
		opts...,
	)
	agentServiceRegisterProviderHandler := connect_go.NewUnaryHandler(
		AgentServiceRegisterProviderProcedure,
		svc.RegisterProvider,
		opts...,
	)
	agentServiceDeleteProviderHandler := connect_go.NewUnaryHandler(
		AgentServiceDeleteProviderProcedure,
		svc.DeleteProvider,
		opts...,
	)
	agentServiceTestProviderHandler := connect_go.NewUnaryHandler(
		AgentServiceTestProviderProcedure,
		svc.TestProvider,
		opts...,
	)
	agentServiceListModelsHandler := connect_go.NewUnaryHandler(
		AgentServiceListModelsProcedure,
		svc.ListModels,
		opts...,
	)
	agentServiceListPresetsHandler := connect_go.NewUnaryHandler(
		AgentServiceListPresetsProcedure,
		svc.ListPresets,
		opts...,
	)
	agentServiceUpsertPresetHandler := connect_go.NewUnaryHandler(
		AgentServiceUpsertPresetProcedure,
		svc.UpsertPreset,
		opts...,
	)
	agentServiceDeletePresetHandler := connect_go.NewUnaryHandler(
		AgentServiceDeletePresetProcedure,
		svc.DeletePreset,
		opts...,
	)
	agentServicePreviewPresetHandler := connect_go.NewUnaryHandler(
		AgentServicePreviewPresetProcedure,
		svc.PreviewPreset,
		opts...,
	)
	agentServiceGetConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceGetConfigProcedure,
		svc.GetConfig,
		opts...,
	)
	agentServiceSetConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceSetConfigProcedure,
		svc.SetConfig,
		opts...,
	)
	agentServiceListToolsHandler := connect_go.NewUnaryHandler(
		AgentServiceListToolsProcedure,
		svc.ListTools,
		opts...,
	)
	agentServiceGetToolConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceGetToolConfigProcedure,
		svc.GetToolConfig,
		opts...,
	)
	agentServiceSetToolConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceSetToolConfigProcedure,
		svc.SetToolConfig,
		opts...,
	)
	agentServiceSetExtensionConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceSetExtensionConfigProcedure,
		svc.SetExtensionConfig,
		opts...,
	)
	agentServiceUploadFileHandler := connect_go.NewUnaryHandler(
		AgentServiceUploadFileProcedure,
		svc.UploadFile,
		opts...,
	)
	agentServiceIngestFileHandler := connect_go.NewUnaryHandler(
		AgentServiceIngestFileProcedure,
		svc.IngestFile,
		opts...,
	)
	agentServiceGetFileHandler := connect_go.NewUnaryHandler(
		AgentServiceGetFileProcedure,
		svc.GetFile,
		opts...,
	)
	agentServiceGetFileMetaHandler := connect_go.NewUnaryHandler(
		AgentServiceGetFileMetaProcedure,
		svc.GetFileMeta,
		opts...,
	)
	agentServiceGetAgentConfigHandler := connect_go.NewUnaryHandler(
		AgentServiceGetAgentConfigProcedure,
		svc.GetAgentConfig,
		opts...,
	)
	return "/agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceHealthProcedure:
			agentServiceHealthHandler.ServeHTTP(w, r)
		case AgentServiceListSessionsProcedure:
			agentServiceListSessionsHandler.ServeHTTP(w, r)
		case AgentServiceCreateSessionProcedure:
			agentServiceCreateSessionHandler.ServeHTTP(w, r)
		case AgentServiceGetSessionProcedure:
			agentServiceGetSessionHandler.ServeHTTP(w, r)
		case AgentServiceDeleteSessionProcedure:
			agentServiceDeleteSessionHandler.ServeHTTP(w, r)
		case AgentServiceListMessagesProcedure:
			agentServiceListMessagesHandler.ServeHTTP(w, r)
		case AgentServicePromptProcedure:
			agentServicePromptHandler.ServeHTTP(w, r)
		case AgentServiceWatchSessionProcedure:
			agentServiceWatchSessionHandler.ServeHTTP(w, r)
		case AgentServiceForkProcedure:
			agentServiceForkHandler.ServeHTTP(w, r)
		case AgentServiceRenameProcedure:
			agentServiceRenameHandler.ServeHTTP(w, r)
		case AgentServiceSetModelProcedure:
			agentServiceSetModelHandler.ServeHTTP(w, r)
		case AgentServiceUndoProcedure:
			agentServiceUndoHandler.ServeHTTP(w, r)
		case AgentServiceStateProcedure:
			agentServiceStateHandler.ServeHTTP(w, r)
		case AgentServiceMailboxProcedure:
			agentServiceMailboxHandler.ServeHTTP(w, r)
		case AgentServiceUpdateSettingsProcedure:
			agentServiceUpdateSettingsHandler.ServeHTTP(w, r)
		case AgentServiceInterruptProcedure:
			agentServiceInterruptHandler.ServeHTTP(w, r)
		case AgentServiceCompactProcedure:
			agentServiceCompactHandler.ServeHTTP(w, r)
		case AgentServiceListProvidersProcedure:
			agentServiceListProvidersHandler.ServeHTTP(w, r)
		case AgentServiceListProvidersCatalogProcedure:
			agentServiceListProvidersCatalogHandler.ServeHTTP(w, r)
		case AgentServiceRegisterProviderProcedure:
			agentServiceRegisterProviderHandler.ServeHTTP(w, r)
		case AgentServiceDeleteProviderProcedure:
			agentServiceDeleteProviderHandler.ServeHTTP(w, r)
		case AgentServiceTestProviderProcedure:
			agentServiceTestProviderHandler.ServeHTTP(w, r)
		case AgentServiceListModelsProcedure:
			agentServiceListModelsHandler.ServeHTTP(w, r)
		case AgentServiceListPresetsProcedure:
			agentServiceListPresetsHandler.ServeHTTP(w, r)
		case AgentServiceUpsertPresetProcedure:
			agentServiceUpsertPresetHandler.ServeHTTP(w, r)
		case AgentServiceDeletePresetProcedure:
			agentServiceDeletePresetHandler.ServeHTTP(w, r)
		case AgentServicePreviewPresetProcedure:
			agentServicePreviewPresetHandler.ServeHTTP(w, r)
		case AgentServiceGetConfigProcedure:
			agentServiceGetConfigHandler.ServeHTTP(w, r)
		case AgentServiceSetConfigProcedure:
			agentServiceSetConfigHandler.ServeHTTP(w, r)
		case AgentServiceListToolsProcedure:
			agentServiceListToolsHandler.ServeHTTP(w, r)
		case AgentServiceGetToolConfigProcedure:
			agentServiceGetToolConfigHandler.ServeHTTP(w, r)
		case AgentServiceSetToolConfigProcedure:
			agentServiceSetToolConfigHandler.ServeHTTP(w, r)
		case AgentServiceSetExtensionConfigProcedure:
			agentServiceSetExtensionConfigHandler.ServeHTTP(w, r)
		case AgentServiceUploadFileProcedure:
			agentServiceUploadFileHandler.ServeHTTP(w, r)
		case AgentServiceIngestFileProcedure:
			agentServiceIngestFileHandler.ServeHTTP(w, r)
		case AgentServiceGetFileProcedure:
			agentServiceGetFileHandler.ServeHTTP(w, r)
		case AgentServiceGetFileMetaProcedure:
			agentServiceGetFileMetaHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentConfigProcedure:
			agentServiceGetAgentConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Health(context.Context, *connect_go.Request[v1.HealthRequest]) (*connect_go.Response[v1.HealthResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Health is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListSessions(context.Context, *connect_go.Request[v1.ListSessionsRequest]) (*connect_go.Response[v1.ListSessionsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListSessions is not implemented"))
}

func (UnimplementedAgentServiceHandler) CreateSession(context.Context, *connect_go.Request[v1.CreateSessionRequest]) (*connect_go.Response[v1.CreateSessionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.CreateSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetSession(context.Context, *connect_go.Request[v1.GetSessionRequest]) (*connect_go.Response[v1.GetSessionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteSession(context.Context, *connect_go.Request[v1.DeleteSessionRequest]) (*connect_go.Response[v1.DeleteSessionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.DeleteSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListMessages(context.Context, *connect_go.Request[v1.ListMessagesRequest]) (*connect_go.Response[v1.ListMessagesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListMessages is not implemented"))
}

func (UnimplementedAgentServiceHandler) Prompt(context.Context, *connect_go.Request[v1.PromptRequest], *connect_go.ServerStream[v1.PromptResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Prompt is not implemented"))
}

func (UnimplementedAgentServiceHandler) WatchSession(context.Context, *connect_go.Request[v1.WatchSessionRequest], *connect_go.ServerStream[v1.WatchSessionResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.WatchSession is not implemented"))
}

func (UnimplementedAgentServiceHandler) Fork(context.Context, *connect_go.Request[v1.ForkRequest]) (*connect_go.Response[v1.ForkResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Fork is not implemented"))
}

func (UnimplementedAgentServiceHandler) Rename(context.Context, *connect_go.Request[v1.RenameRequest]) (*connect_go.Response[v1.RenameResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Rename is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetModel(context.Context, *connect_go.Request[v1.SetModelRequest]) (*connect_go.Response[v1.SetModelResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.SetModel is not implemented"))
}

func (UnimplementedAgentServiceHandler) Undo(context.Context, *connect_go.Request[v1.UndoRequest]) (*connect_go.Response[v1.UndoResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Undo is not implemented"))
}

func (UnimplementedAgentServiceHandler) State(context.Context, *connect_go.Request[v1.StateRequest]) (*connect_go.Response[v1.StateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.State is not implemented"))
}

func (UnimplementedAgentServiceHandler) Mailbox(context.Context, *connect_go.Request[v1.MailboxRequest]) (*connect_go.Response[v1.MailboxResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Mailbox is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateSettings(context.Context, *connect_go.Request[v1.UpdateSettingsRequest]) (*connect_go.Response[v1.UpdateSettingsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.UpdateSettings is not implemented"))
}

func (UnimplementedAgentServiceHandler) Interrupt(context.Context, *connect_go.Request[v1.InterruptRequest]) (*connect_go.Response[v1.InterruptResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Interrupt is not implemented"))
}

func (UnimplementedAgentServiceHandler) Compact(context.Context, *connect_go.Request[v1.CompactRequest]) (*connect_go.Response[v1.CompactResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.Compact is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListProviders(context.Context, *connect_go.Request[v1.ListProvidersRequest]) (*connect_go.Response[v1.ListProvidersResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListProviders is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListProvidersCatalog(context.Context, *connect_go.Request[v1.ListProvidersCatalogRequest]) (*connect_go.Response[v1.ListProvidersCatalogResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListProvidersCatalog is not implemented"))
}

func (UnimplementedAgentServiceHandler) RegisterProvider(context.Context, *connect_go.Request[v1.RegisterProviderRequest]) (*connect_go.Response[v1.RegisterProviderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.RegisterProvider is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteProvider(context.Context, *connect_go.Request[v1.DeleteProviderRequest]) (*connect_go.Response[v1.DeleteProviderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.DeleteProvider is not implemented"))
}

func (UnimplementedAgentServiceHandler) TestProvider(context.Context, *connect_go.Request[v1.TestProviderRequest]) (*connect_go.Response[v1.TestProviderResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.TestProvider is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListModels(context.Context, *connect_go.Request[v1.ListModelsRequest]) (*connect_go.Response[v1.ListModelsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListModels is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListPresets(context.Context, *connect_go.Request[v1.ListPresetsRequest]) (*connect_go.Response[v1.ListPresetsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListPresets is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpsertPreset(context.Context, *connect_go.Request[v1.UpsertPresetRequest]) (*connect_go.Response[v1.UpsertPresetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.UpsertPreset is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeletePreset(context.Context, *connect_go.Request[v1.DeletePresetRequest]) (*connect_go.Response[v1.DeletePresetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.DeletePreset is not implemented"))
}

func (UnimplementedAgentServiceHandler) PreviewPreset(context.Context, *connect_go.Request[v1.PreviewPresetRequest]) (*connect_go.Response[v1.PreviewPresetResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.PreviewPreset is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetConfig(context.Context, *connect_go.Request[v1.GetConfigRequest]) (*connect_go.Response[v1.GetConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetConfig(context.Context, *connect_go.Request[v1.SetConfigRequest]) (*connect_go.Response[v1.SetConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.SetConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListTools(context.Context, *connect_go.Request[v1.ListToolsRequest]) (*connect_go.Response[v1.ListToolsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.ListTools is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetToolConfig(context.Context, *connect_go.Request[v1.GetToolConfigRequest]) (*connect_go.Response[v1.GetToolConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetToolConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetToolConfig(context.Context, *connect_go.Request[v1.SetToolConfigRequest]) (*connect_go.Response[v1.SetToolConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.SetToolConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetExtensionConfig(context.Context, *connect_go.Request[v1.SetExtensionConfigRequest]) (*connect_go.Response[v1.SetExtensionConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.SetExtensionConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) UploadFile(context.Context, *connect_go.Request[v1.UploadFileRequest]) (*connect_go.Response[v1.UploadFileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.UploadFile is not implemented"))
}

func (UnimplementedAgentServiceHandler) IngestFile(context.Context, *connect_go.Request[v1.IngestFileRequest]) (*connect_go.Response[v1.IngestFileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.IngestFile is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetFile(context.Context, *connect_go.Request[v1.GetFileRequest]) (*connect_go.Response[v1.GetFileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetFile is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetFileMeta(context.Context, *connect_go.Request[v1.GetFileMetaRequest]) (*connect_go.Response[v1.GetFileMetaResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetFileMeta is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgentConfig(context.Context, *connect_go.Request[v1.GetAgentConfigRequest]) (*connect_go.Response[v1.GetAgentConfigResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("agent.v1.AgentService.GetAgentConfig is not implemented"))
}
